project_id = "hqrmahicnkdnuvtbqwob"
[functions.environment]
N8N_WEBHOOK_URL = "https://primary-production-90b2.up.railway.app/webhook/b76bdc69-7e22-42f4-95a6-f84e85add767"


[functions.generate-document-pdf]
verify_jwt = true