// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqrmahicnkdnuvtbqwob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxcm1haGljbmtkbnV2dGJxd29iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjIzMDksImV4cCI6MjA2NjkzODMwOX0.sV_mmDl0eChvPoekuijK7Eby-1nYhuxAcgiwOfpdEZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});